cam0:
  cam_cx: 609.5593
  cam_cy: 172.854
  cam_d0: 0.0
  cam_d1: 0.0
  cam_d2: 0.0
  cam_d3: 0.0
  cam_fx: 721.5377
  cam_fy: 721.5377
  cam_bl: 0.537150588
  cam_height: 375
  cam_model: Pinhole
  cam_width: 1242
  rx: 0.0
  ry: 0.0
  rz: 0.0
  tx: 0.0
  ty: 0.0
  tz: 0.0
images_subfolder_l: image_2/
images_subfolder_r: image_3/
